environment:
    DEBUG: "1"
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
branches:
    only:
        - master
install:
    - "%PYTHON%\\python.exe -m pip install pylint pytest psutil"
build: off
test_script:
    - "%PYTHON%\\python.exe -m pytest tests.py -v && %PYTHON%\\python.exe -m pylint --errors-only --ignore=testff.py ffpuppet"
