language: python
python:
    - 2.7
branches:
    only:
        - master
before_script:
    - pip install pylint pytest-cov python-coveralls psutil xvfbwrapper
script:
    - py.test tests.py -v --cov . --cov-report term-missing --cov-config .coveragerc && pylint --errors-only --ignore=testff.py ffpuppet
after_success:
    - coveralls
