language: python
python:
    - 2.7
branches:
    only:
        - master
before_script:
    - pip install pytest-cov python-coveralls psutil xvfbwrapper
script:
    - py.test tests.py -v --cov . --cov-report term-missing
after_success:
    - coveralls
