language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
branches:
    only:
        - master
before_script:
    - sudo apt-get install gdb
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then pip install psutil pylint pytest-cov python-coveralls xvfbwrapper; else pip install psutil xvfbwrapper; fi
script:
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then py.test tests.py -v --cov . --cov-report term-missing --cov-config .coveragerc && pylint --errors-only --ignore=testff.py ffpuppet; else py.test tests.py -v; fi
after_success:
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then coveralls; fi
